In [1]:
import torch
import torch.nn as nn

In [2]:
class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)

    return out

In [3]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.5373],
        [0.5292],
        [0.5277],
        [0.5352],
        [0.5258],
        [0.5292],
        [0.5311],
        [0.5272],
        [0.5245],
        [0.5317]], grad_fn=<SigmoidBackward0>)

In [4]:
model.network[0].weight

Parameter containing:
tensor([[-0.2782,  0.2898,  0.3327,  0.4166,  0.1581],
        [-0.1645, -0.1095, -0.4006, -0.2884,  0.1283],
        [-0.3735, -0.2563,  0.0639, -0.1709, -0.3920]], requires_grad=True)

In [5]:
model.network[0].bias

Parameter containing:
tensor([0.1989, 0.2879, 0.0729], requires_grad=True)

In [6]:
!pip install torchinfo

In [7]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00